apiVersion: "networking.istio.io/v1beta1"
kind: "Gateway"
metadata:
  name: "ingressgateway"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  selector:
    istio: "ingressgateway"
  servers:
    # This port is reserved for the apiclient. For more information see the
    # following files.
    #
    #     ./env/knd/istio.yaml
    #     ./env/knd/kind.yaml
    #
    - port:
        name: "apiclient"
        number: 30003
        protocol: "HTTP"
      hosts:
        - "*"
    # This port is reserved for the apiserver. For more information see the
    # following files.
    #
    #     ./env/knd/istio.yaml
    #     ./env/knd/kind.yaml
    #
    - port:
        name: "apiserver"
        number: 30007
        protocol: "GRPC"
      hosts:
        - "*"
