apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "ingressgateway"
spec:
  dnsNames:
    - "*.{{ .Values.cluster.name }}.{{ .Values.cluster.zone }}"
  duration: "2160h"
  issuerRef:
    kind: "ClusterIssuer"
    name: "letsencrypt"
  renewBefore: "720h"
  secretName: "ingressgateway"
