apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "letsencrypt"
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "xh3b4sd@gmail.com"
    privateKeySecretRef:
      name: "letsencrypt"
    solvers:
      - dns01:
          route53:
            accessKeyID: "{{ .Values.aws.accessid }}"
            region: "{{ .Values.aws.region }}"
            secretAccessKeySecretRef:
              name: "aws"
              key: "secretid"
