apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "letsencrypt-route53"
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "xh3b4sd@gmail.com"
    privateKeySecretRef:
      name: "letsencrypt-route53"
    solvers:
      - dns01:
          route53:
            accessKeyID: "{{ .Values.aws.accessid }}"
            region: "{{ .Values.aws.region }}"
            secretAccessKeySecretRef:
              name: "aws"
              key: "secretid"
---
apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "letsencrypt-cloudflare"
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "xh3b4sd@gmail.com"
    privateKeySecretRef:
      name: "letsencrypt-cloudflare"
    solvers:
      - dns01:
          cloudflare:
            email: "marcus@venturemark.co"
            apiTokenSecretRef:
              name: "cloudflare"
              key: "token"
