apiVersion: "v1"
kind: "Secret"
metadata:
  name: "aws"
type: "Opaque"
data:
  secretid: "{{ .Values.aws.secretid | b64enc }}"
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "cloudflare"
type: "Opaque"
data:
  token: "{{ .Values.cloudflare.token | b64enc }}"
