apiVersion: "install.istio.io/v1alpha1"
kind: "IstioOperator"
spec:
  components:
    ingressGateways:
      - name: "istio-ingressgateway"
        enabled: true
        k8s:
          overlays:
            - apiVersion: "v1"
              kind: "Service"
              name: "istio-ingressgateway"
              patches:
                # The webclient port mapping works as follows.
                #
                #      host       |                container                |        k8s
                #
                #     :3000    <----->    :30003    <----->    :30003    <----->    :3000
                #
                - path: "spec.ports[4]"
                  value:
                    name: "webclient"
                    nodePort: 30003
                    port: 30003
                    targetPort: 3000

                # The apiserver port mapping works as follows.
                #
                #      host       |                container                |        k8s
                #
                #     :7777    <----->    :30007    <----->    :30007    <----->    :7777
                #
                - path: "spec.ports[5]"
                  value:
                    name: "apiserver"
                    nodePort: 30007
                    port: 30007
                    targetPort: 7777

                # The prometheus port mapping works as follows.
                #
                #      host       |                container                |        k8s
                #
                #     :9090    <----->    :30009    <----->    :30009    <----->    :9090
                #
                - path: "spec.ports[6]"
                  value:
                    name: "prometheus"
                    nodePort: 30009
                    port: 30009
                    targetPort: 9090

                # The prometheus port mapping works as follows.
                #
                #      host       |                container                |        k8s
                #
                #     :3030    <----->    :30030    <----->    :30030    <----->    :3030
                #
                - path: "spec.ports[7]"
                  value:
                    name: "prometheus"
                    nodePort: 30030
                    port: 30030
                    targetPort: 3030
    pilot:
      k8s:
        # We limit the resources istiod consumes in the local setup. The pilot
        # component configures e.g. the istiod deployment, for whatever reason.
        # So during development it should not be necessary to allocate 2GB by
        # default, because that would just steal resources unnecessarily from
        # all the other pods we have to run.
        resources:
          limits:
            cpu: "200m"
            memory: "500Mi"
          requests:
            cpu: "200m"
            memory: "500Mi"
  meshConfig:
    accessLogFile: /dev/stdout
