kind: "ClusterConfig"
apiVersion: "eksctl.io/v1alpha5"

metadata:
  name: "{{ .Cluster.Name }}"
  region: "{{ .AWS.Region }}"

nodeGroups:
  - name: "ng001"
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
    instanceType: "t3.large"
    ssh:
      allow: false
    volumeSize: 100

vpc:
  nat:
    gateway: "HighlyAvailable"
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
